package com.example.mainpage_subapp.roomdata;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;


//room automatically creates a table for any class that is annotated with the Entity tag
@Entity(tableName = "subscriptions")
public class Subscription {

    //primary key is auto generated ID for now - tell me if you want to change this
    @PrimaryKey(autoGenerate = true)
    private int id;

    //room adds columns with the help of annotated ColumnInfo tags automatically
    //by default, columninfo takes the var name as the column name but i've done it explicitly here either way
    @ColumnInfo(name = "name") private String name;

    @ColumnInfo(name = "plan") private String plan;

    @ColumnInfo(name = "price") private int price;

    @ColumnInfo(name = "shared") private int shared;

    @ColumnInfo(name = "billing_cycle") private int billing_cycle;

    @ColumnInfo(name = "icon") private int icon;

    @ColumnInfo(name = "start_date") private String start_date;

    //creating a constructor - we need these to create Subscription objects
    // and room needs a constructor to recreate this database whenever necessary

    //no id in constructor since it is autogenerated

    public Subscription(String name, String plan, int price, int shared, int billing_cycle, int icon, String start_date) {
        this.name = name;
        this.plan = plan;
        this.price = price;
        this.shared = shared;
        this.billing_cycle = billing_cycle;
        this.icon = icon;
        this.start_date = start_date;
    }


    //apparently you also need to create getter methods for all the entities (including id) for persistence or smth
    //i didnt really find much info on this but creating them for now anyway

    //also a heads up i didn't know this - you can right click - generate - and create getters, constructors etc automatically
    // v cool

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getPlan() {
        return plan;
    }

    public int getPrice() {
        return price;
    }

    public int getShared() {
        return shared;
    }

    public int getBilling_cycle() {
        return billing_cycle;
    }

    public int getIcon() {
        return icon;
    }

    public String getStart_date(){
        return start_date;
    }
    //finally, you need a setter for the id for room to be able to access it

    public void setId(int id) {
        this.id = id;
    }

}
